-- Tabelle
CREATE TABLE PDSSTRUTTURE(IDSTRUTTURE NUMBER NOT NULL, 
 ASL VARCHAR2(6), 
 DENOMINAZIONESTRUTTURA VARCHAR2(80)NOT NULL, 
 NUMEROAUTORIZZAZIONE VARCHAR2(50), --chiave per identificare le strutture private
 DATAAUTORIZZAZIONE DATE, --chiave per identificare le strutture private
 ISTATCOMUNE VARCHAR2(6), 
 CAP VARCHAR2(5), 
 INDIRIZZO VARCHAR2(200), 
 CIVICO VARCHAR2(10), 
 TELEFONO VARCHAR2(80), 
 IDMEDICOCERTIFICATORE NUMBER(22), -- > ???
 IDUFFICIO NUMBER(22)); 
 
ALTER TABLE UFFICI ADD(
 DATAAUTORIZZAZIONE DATE, 
 NUMEROAUTORIZZAZIONE VARCHAR2(80)); 
 
CREATE TABLE PDSISTANZEMEDICI(IDISTANZEMEDICI NUMBER NOT NULL, 
 TIPOISTANZA VARCHAR2(50)NOT NULL, 
 DATAORAINVIO DATE NOT NULL, 
 DATAORAPROTOCOLLO DATE, 
 NUMEROPROTOCOLLO VARCHAR2(50), 
 DATASCADENZA DATE, 
 VARIABILE CHAR(1)DEFAULT '0' NOT NULL, 
 CANCELLABILE CHAR(1)DEFAULT '0' NOT NULL, 
 RINNOVABILE CHAR(1)DEFAULT '0' NOT NULL, 
 SCARICABILE CHAR(1)DEFAULT '0' NOT NULL, 
 COGNOME VARCHAR2(80)NOT NULL, 
 NOME VARCHAR2(80)NOT NULL, 
 CODICEFISCALE VARCHAR2(16), 
 DATADINASCITA DATE, 
 ISTATCOMUNENASCITA VARCHAR2(6), 
 ISTATSTATOESTERONASCITA VARCHAR2(6), 
 ISTATCOMUNERESIDENZA VARCHAR2(6), 
 CAPRESIDENZA VARCHAR2(5), 
 INDIRIZZORESIDENZA VARCHAR2(200), 
 CIVICORESIDENZA VARCHAR2(10), 
 TELEFONO VARCHAR2(80), 
 EMAIL VARCHAR2(80), 
 PEC VARCHAR2(80), 
 DATASPECIALIZZAZIONE DATE, 
 UNIVERSITASPECIALIZZAZIONE VARCHAR2(200), 
 PROVINCIAISCRIZIONEORDINE VARCHAR2(2), 
 NUMEROISCRIZIONEORDINE VARCHAR2(50), 
 IDMEDICO NUMBER(22)); -- > MEDICI
 
CREATE TABLE PDSISTANZAMEDICOSTRUTTURE(--IDISTANZAMEDICOSTRUTTURE NUMBER NOT NULL, 
 IDISTANZAMEDICO NUMBER(22), 
 IDSTRUTTURA NUMBER(22)NOT NULL); 
 
CREATE TABLE PDSISTANZAMEDICODISCIPLINE(--IDISTANZAMEDICODISCIPLINE NUMBER NOT NULL, 
 IDISTANZAMEDICO NUMBER(22), 
 IDDISCIPLINA NUMBER(22)NOT NULL); --relazione con Tabelle.idTabelle
 
CREATE TABLE MEDICODISCIPLINESPORTIVE(--IDMEDICODISCIPLINESPORTIVE NUMBER NOT NULL, 
 IDMEDICO NUMBER(22), --relazione con Medici
 IDDISCIPLINA NUMBER(22)NOT NULL); --relazione con Tabelle.idTabelle
 
 -- Chiavi priimarie
ALTER TABLE PDSSTRUTTURE ADD CONSTRAINT PDSSTRUTTURE1 PRIMARY KEY(IDSTRUTTURE);
ALTER TABLE PDSISTANZEMEDICI ADD CONSTRAINT PDSISTANZEMEDICI1 PRIMARY KEY(IDISTANZEMEDICI);
-- Indici
CREATE UNIQUE INDEX PDSISTANZAMEDICOSTRUTTURE1 ON PDSISTANZAMEDICOSTRUTTURE(IDISTANZAMEDICO,IDSTRUTTURA);
CREATE UNIQUE INDEX PDSISTANZAMEDICODISCIPLINE1 ON PDSISTANZAMEDICODISCIPLINE(IDISTANZAMEDICO,IDDISCIPLINA);
CREATE UNIQUE INDEX MEDICODISCIPLINESPORTIVE1 ON MEDICODISCIPLINESPORTIVE(IDMEDICO,IDDISCIPLINA);
-- Relazioni
ALTER TABLE PDSSTRUTTURE ADD CONSTRAINT FK_PDSSTRUTTURE1 FOREIGN KEY (IDUFFICIO) REFERENCES UFFICI(IDUFFICI);
ALTER TABLE PDSISTANZEMEDICI ADD CONSTRAINT FK_PDSISTANZEMEDICI1 FOREIGN KEY (IDMEDICO) REFERENCES MEDICI(IDMEDICI);
ALTER TABLE PDSISTANZAMEDICOSTRUTTURE ADD CONSTRAINT FK_PDSISTANZAMEDICOSTRUTTURE1 FOREIGN KEY (IDISTANZAMEDICO) REFERENCES PDSISTANZEMEDICI(IDISTANZEMEDICI);
ALTER TABLE PDSISTANZAMEDICOSTRUTTURE ADD CONSTRAINT FK_PDSISTANZAMEDICOSTRUTTURE2 FOREIGN KEY (IDSTRUTTURA) REFERENCES PDSSTRUTTURE(IDSTRUTTURE);
ALTER TABLE PDSISTANZAMEDICODISCIPLINE ADD CONSTRAINT FK_PDSISTANZAMEDICODISCIPLINE1 FOREIGN KEY (IDISTANZAMEDICO) REFERENCES PDSISTANZEMEDICI(IDISTANZEMEDICI);
ALTER TABLE PDSISTANZAMEDICODISCIPLINE ADD CONSTRAINT FK_PDSISTANZAMEDICODISCIPLINE2 FOREIGN KEY (IDDISCIPLINA) REFERENCES TABELLE(IDTABELLE);
ALTER TABLE MEDICODISCIPLINESPORTIVE ADD CONSTRAINT FK_MEDICODISCIPLINESPORTIVE1 FOREIGN KEY (IDMEDICO) REFERENCES MEDICI(IDMEDICI);
ALTER TABLE MEDICODISCIPLINESPORTIVE ADD CONSTRAINT FK_MEDICODISCIPLINESPORTIVE2 FOREIGN KEY (IDDISCIPLINA) REFERENCES TABELLE(IDTABELLE);